#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT}"

AUDIT_DOC="docs/FCP3_Crate_Graph_Audit.md"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required to compute forbidden-overlap status" >&2
  exit 1
fi

if [[ ! -f "${AUDIT_DOC}" ]]; then
  echo "missing ${AUDIT_DOC}" >&2
  exit 1
fi

HOLDOUTS_JSON='[
  {
    "id": "I2-HOST-MESH",
    "from": "fcp-host",
    "to": "fcp-mesh",
    "type_name": "SimulateResourceAvailability / mesh placement availability summary",
    "canonical_path": "fcp-mesh::planner::ResourcePoolDecisionSummary",
    "status": "pending",
    "detail_bead": "flywheel_connectors-angoc.3.3"
  },
  {
    "id": "I2-STORE-RAPTORQ",
    "from": "fcp-store",
    "to": "fcp-raptorq",
    "type_name": "ObjectTransmissionInfo / RaptorQ transmission metadata",
    "canonical_path": "fcp-raptorq::ObjectTransmissionInformation",
    "status": "pending",
    "detail_bead": "flywheel_connectors-angoc.3.4"
  },
  {
    "id": "I2-PROTOCOL-CRYPTO",
    "from": "fcp-protocol",
    "to": "fcp-crypto",
    "type_name": "SignedEnvelope / hybrid signed-object envelope",
    "canonical_path": "fcp-crypto::SignedEnvelope",
    "status": "pending",
    "detail_bead": "flywheel_connectors-angoc.3.5"
  }
]'

metadata="$(cargo metadata --format-version 1)"
rows_json="$(
  jq -c --argjson holdouts "${HOLDOUTS_JSON}" '
    def pkg_exists($meta; $name):
      any($meta.packages[]; .name == $name);
    def direct_dep($meta; $from; $to):
      any($meta.packages[];
        .name == $from
        and any((.dependencies // [])[]; .name == $to and (.path != null))
      );
    . as $meta
    |
    $holdouts[]
    | . + {
        from_exists: pkg_exists($meta; .from),
        to_exists: pkg_exists($meta; .to),
        from_depends_to: direct_dep($meta; .from; .to),
        to_depends_from: direct_dep($meta; .to; .from)
      }
  ' <<<"${metadata}"
)"

table_rows=""
machine_rows=""
pending_count=0
resolved_count=0
current_count=0

while IFS= read -r row; do
  [[ -z "${row}" ]] && continue

  id="$(jq -r '.id' <<<"${row}")"
  from_crate="$(jq -r '.from' <<<"${row}")"
  to_crate="$(jq -r '.to' <<<"${row}")"
  type_name="$(jq -r '.type_name' <<<"${row}")"
  canonical_path="$(jq -r '.canonical_path' <<<"${row}")"
  status="$(jq -r '.status' <<<"${row}")"
  detail_bead="$(jq -r '.detail_bead' <<<"${row}")"
  from_depends_to="$(jq -r '.from_depends_to' <<<"${row}")"
  to_depends_from="$(jq -r '.to_depends_from' <<<"${row}")"
  from_exists="$(jq -r '.from_exists' <<<"${row}")"
  to_exists="$(jq -r '.to_exists' <<<"${row}")"

  audit_pair_mentioned=false
  if grep -q -- "${from_crate}" "${AUDIT_DOC}" && grep -q -- "${to_crate}" "${AUDIT_DOC}"; then
    audit_pair_mentioned=true
  fi

  case "${status}" in
    pending)
      ((pending_count += 1))
      ;;
    resolved)
      ((resolved_count += 1))
      ;;
    *)
      echo "unknown overlap status for ${id}: ${status}" >&2
      exit 1
      ;;
  esac
  ((current_count += 1))

  echo "INFO forbidden_overlap id=${id} type_name=${type_name} from_crate=${from_crate} to_crate=${to_crate} canonical_path=${canonical_path} status=${status}" >&2

  relation="none"
  if [[ "${from_depends_to}" == "true" && "${to_depends_from}" == "true" ]]; then
    relation="bidirectional"
  elif [[ "${from_depends_to}" == "true" ]]; then
    relation="${from_crate}->${to_crate}"
  elif [[ "${to_depends_from}" == "true" ]]; then
    relation="${to_crate}->${from_crate}"
  fi

  table_rows+=$'| '"${id}"$' | '"${type_name}"$' | '"${from_crate}"$' | '"${to_crate}"$' | `'"${canonical_path}"$'` | '"${status}"$' | '"${relation}"$' | '"${detail_bead}"$' |\n'
  machine_rows+=$'<!-- forbidden-overlap-row: id='"${id}"$' from='"${from_crate}"$' to='"${to_crate}"$' canonical='"${canonical_path}"$' status='"${status}"$' relation='"${relation}"$' from_exists='"${from_exists}"$' to_exists='"${to_exists}"$' audit_pair_mentioned='"${audit_pair_mentioned}"$' detail_bead='"${detail_bead}"$' -->\n'
done <<<"${rows_json}"

machine_rows="${machine_rows%$'\n'}"

cat <<EOF
# Forbidden Overlap Status

> Bead: \`flywheel_connectors-angoc.3.2\`
> Generated by: \`scripts/cleanup/compute_forbidden_overlap.sh\`
> Source baseline: \`docs/FCP3_Crate_Graph_Audit.md\`
> Current tracker source: \`docs/reality/2026-05-12-reality-check-bridge-plan.md\` Phase I.2

This status file pins the three Phase I.2 holdouts as a forward-only baseline.
The cleanup script uses \`cargo metadata --format-version 1\` plus \`jq\` to
confirm that the crate pairs still exist in the current workspace and to record
the direct dependency relation for each pair.

The older crate-graph audit does not enumerate these three specific pairs as
closed work. This file is the current delta ledger: \`pending=3\` means the
detail beads have been filed, not that the type moves are already complete.

<!-- forbidden-overlap-summary: baseline_pairs=3 current_pairs=${current_count} pending=${pending_count} resolved=${resolved_count} -->

| ID | Type surface | From crate | Canonical owner | Canonical path | Status | Direct dependency | Detail bead |
|----|--------------|------------|-----------------|----------------|--------|-------------------|-------------|
${table_rows}
## Boundary Statements

### I2-HOST-MESH

\`SimulateResourceAvailability\` and any mesh placement availability summary move
out of \`crates/fcp-host/src/admin_state.rs\` into \`fcp-mesh\`, initially adjacent
to \`fcp_mesh::planner::ResourcePoolDecisionSummary\` unless implementation proves
a narrower mesh module. \`fcp-host\` imports the mesh-owned type and remains an
admin/API projection layer only.

### I2-STORE-RAPTORQ

\`ObjectTransmissionInfo\` and any RaptorQ object-transmission metadata wrapper
move from \`crates/fcp-store/src/symbol_store.rs\` to the RaptorQ owner surface.
\`fcp-store\` imports the canonical \`fcp_raptorq::ObjectTransmissionInformation\`
or an explicitly named \`fcp_raptorq\` serde wrapper; it owns persistence
behavior, not RaptorQ metadata semantics.

### I2-PROTOCOL-CRYPTO

Cryptographic signed-envelope semantics stay in \`fcp-crypto\` as
\`fcp_crypto::SignedEnvelope\` and \`fcp_crypto::HybridSignedObjectKind\`.
\`fcp-protocol\` owns only FCPC/FCPS frame and session wire envelopes. Any
protocol payload that needs hybrid signing imports the crypto-owned envelope
instead of defining protocol-local signed-envelope semantics.

## Machine-Readable Rows

${machine_rows}
EOF
